version: '3.9'

networks:
  sibiriana-net:
    external: true

services:
  predict:
    container_name: predict
    restart: always
    image: predict
    build: .
    ports: 
      - 1234:1234
    networks:
      - sibiriana-net
